### ISSUE TITLE
https://sondemigods.github.io/demigods_vuepress/views/Framework/common/standard.html#%E4%BA%8C-vue-%E9%A1%B9%E7%9B%AE%E7%9B%AE%E5%BD%95%E8%A7%84%E8%8C%83

### ISSUE THREAD

**Issue by pengchenggang** [SonDemigods/demigods_vuepress#7]
![image](https://user-images.githubusercontent.com/7833742/102461104-e3667180-4082-11eb-8d95-be506fa45ea0.png)
少个字母h
：）

**Comment by pengchenggang** [comment]
图片没传上去
components
props
data
computed
created
mounted
metods <--- 这个
filter
watch

**Comment by SonDemigods** [comment]
thank you。
This spelling mistake has been fixed。
